### ISSUE TITLE
Package Not Getting Added

### ISSUE THREAD

**Issue by ithinkdancan** [benschwarz/sublime-bower#27]
Running SublimeText 3 (3047) on OSX and I get this error when trying to install a bower package:

```
Exception in thread Thread-18:
Traceback (most recent call last):
  File "X/threading.py", line 639, in _bootstrap_inner
  File "bower.utils.download in /Users/ithinkdancan/Library/Application Support/Sublime Text 3/Installed Packages/Bower.sublime-package", line 22, in run
  File "bower.utils.download in /Users/ithinkdancan/Library/Application Support/Sublime Text 3/Installed Packages/Bower.sublime-package", line 26, in install_package
  File "bower.utils.cli in /Users/ithinkdancan/Library/Application Support/Sublime Text 3/Installed Packages/Bower.sublime-package", line 46, in execute
Bower.bower.exceptions.non_clean_exit_error.NonCleanExitError: 1
```

**Comment by benschwarz** [comment]
Hmm, I just tested on my local copy here and it worked ok.
Have you separately verified that bower is working a-okay?

**Comment by npercell** [comment]
I'm having what appears to be this same issue. It says it is downloading but no files appear to be created and this error appears: 
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/threading.py", line 532, in __bootstrap_inner
  File "./bower/utils/download.py", line 22, in run
  File "./bower/utils/download.py", line 26, in install_package
  File "./bower/utils/cli.py", line 46, in execute
NonCleanExitError: 1

**Comment by npercell** [comment]
Oh, and bower does appear to be working correctly from the command line.

**Comment by benschwarz** [comment]
@npercell Can you let me know of your bower version and platform… I'll investigate further

**Comment by npercell** [comment]
Bower is version 1.2.7 and I am on OSX 10.8.5.

**Comment by db** [comment]
Same here. ST3 3047, Bower 1.2.7, Windows 8.1 - Ok from the command line. Let me know if you'd like more infos.

**Comment by benschwarz** [comment]
@npercell ST3?

**Comment by tmikaeld** [comment]
Same problem here. 

ST3 3059, OS X 10.9.1 Mavericks.

Full exception:

```
Exception in thread Thread-14:
Traceback (most recent call last):
  File "X/threading.py", line 639, in _bootstrap_inner
  File "bower.utils.download in /Users/nisse/Library/Application Support/Sublime Text 3/Installed Packages/Bower.sublime-package", line 22, in run
  File "bower.utils.download in /Users/nisse/Library/Application Support/Sublime Text 3/Installed Packages/Bower.sublime-package", line 26, in install_package
  File "bower.utils.cli in /Users/nisse/Library/Application Support/Sublime Text 3/Installed Packages/Bower.sublime-package", line 39, in execute
  File "X/subprocess.py", line 818, in __init__
  File "X/subprocess.py", line 1347, in _execute_child
  File "X/os.py", line 800, in fsencode
TypeError: expect bytes or str, not NoneType

Exception in thread Thread-19:
Traceback (most recent call last):
  File "X/threading.py", line 639, in _bootstrap_inner
  File "bower.utils.download in /Users/nisse/Library/Application Support/Sublime Text 3/Installed Packages/Bower.sublime-package", line 22, in run
  File "bower.utils.download in /Users/nisse/Library/Application Support/Sublime Text 3/Installed Packages/Bower.sublime-package", line 26, in install_package
  File "bower.utils.cli in /Users/nisse/Library/Application Support/Sublime Text 3/Installed Packages/Bower.sublime-package", line 46, in execute
Bower.bower.exceptions.non_clean_exit_error.NonCleanExitError: 1
```

Tried to install bootstrap3-less package.
