### ISSUE TITLE
Bower: Install not working

### ISSUE THREAD

**Issue by Luluqz** [benschwarz/sublime-bower#41]
I've followed this https://github.com/benschwarz/sublime-bower to install sublime-bower.
Bower works with window 7 Terminal but not with the command palette on ST. 
"Bower: Install" doesn't show any list, insteed, i got this error in the ST console : 

Traceback (most recent call last):
  File "C:\Program Files (x86)\Sublime Text 3\sublime_plugin.py", line 526, in run_
    return self.run()
  File "bower.commands.install in C:\Users\Lulu\AppData\Roaming\Sublime Text 3\Installed Packages\Bower.sublime-package", line 22, in run
  File "bower.commands.install in C:\Users\Lulu\AppData\Roaming\Sublime Text 3\Installed Packages\Bower.sublime-package", line 26, in list_packages
  File "bower.commands.install in C:\Users\Lulu\AppData\Roaming\Sublime Text 3\Installed Packages\Bower.sublime-package", line 56, in get_registry_url
  File "bower.commands.install in C:\Users\Lulu\AppData\Roaming\Sublime Text 3\Installed Packages\Bower.sublime-package", line 44, in get_bower_config
  File "bower.commands.install in C:\Users\Lulu\AppData\Roaming\Sublime Text 3\Installed Packages\Bower.sublime-package", line 17, in get_config_path
  File "X/ntpath.py", line 316, in dirname
  File "X/ntpath.py", line 280, in split
  File "X/ntpath.py", line 208, in splitdrive
TypeError: object of type 'NoneType' has no len()

**Comment by ejbig** [comment]
I've got the same error as you. I hope this issue gets re-solved as soon as possible. 

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 526, in run_
    return self.run()
  File "bower.commands.install in C:\Users\PornPornPorn\AppData\Roaming\Sublime Text 3\Installed Packages\Bower.sublime-package", line 22, in run
  File "bower.commands.install in C:\Users\PornPornPorn\AppData\Roaming\Sublime Text 3\Installed Packages\Bower.sublime-package", line 26, in list_packages
  File "bower.commands.install in C:\Users\PornPornPorn\AppData\Roaming\Sublime Text 3\Installed Packages\Bower.sublime-package", line 56, in get_registry_url
  File "bower.commands.install in C:\Users\PornPornPorn\AppData\Roaming\Sublime Text 3\Installed Packages\Bower.sublime-package", line 44, in get_bower_config
  File "bower.commands.install in C:\Users\PornPornPorn\AppData\Roaming\Sublime Text 3\Installed Packages\Bower.sublime-package", line 17, in get_config_path
  File "X/ntpath.py", line 316, in dirname
  File "X/ntpath.py", line 280, in split
  File "X/ntpath.py", line 208, in splitdrive
TypeError: object of type 'NoneType' has no len()

**Comment by Escapado** [comment]
I also followed the tutorial and I get the same error as the two posters above me. I am on windows 8.1 if that helps. Installed node.js, installed bower through the node.js console, installed msysgit, opened Sublime, installed the bower package through the package manager. Restarted Sublime.. trying to use "Bower Install" will yield the error. Am I missing something?

**Comment by melihovv** [comment]
I've got the same. How to fix it?

**Comment by benschwarz** [comment]
Damn. Someone with some windows experience got some time to look into this? 

---

@Luluqz I'd considered closing / locking this issue on the strength of your avatar. Perhaps you want to reconsider it?

**Comment by kysmet** [comment]
Same error on Ubuntu 14.04 too...any clues how to resolve this.

Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 526, in run_
    return self.run()
  File "bower.commands.install in /home/kysmet/.config/sublime-text-3/Installed Packages/Bower.sublime-package", line 22, in run
  File "bower.commands.install in /home/kysmet/.config/sublime-text-3/Installed Packages/Bower.sublime-package", line 26, in list_packages
  File "bower.commands.install in /home/kysmet/.config/sublime-text-3/Installed Packages/Bower.sublime-package", line 56, in get_registry_url
  File "bower.commands.install in /home/kysmet/.config/sublime-text-3/Installed Packages/Bower.sublime-package", line 44, in get_bower_config
  File "bower.commands.install in /home/kysmet/.config/sublime-text-3/Installed Packages/Bower.sublime-package", line 19, in get_config_path
IndexError: list index out of range

**Comment by mezhgano** [comment]
And i got the same problem, but in my case then i press < bower:install > nothing happen.

**Comment by roman-kuleshov** [comment]
Got the same error. Someone can look into this?

**Comment by benschwarz** [comment]
Sorry folks, I'm not a windows user (windows support was submitted thanks to community contributions) + I don't actually use this plugin myself, so as you can imagine: Its pretty far down my list. 

Can someone help?

**Comment by nwa-app-01** [comment]
Try creating a project.
Use Project/Save Project As ... (then actually save/create a project file).
Then try bower again.

I guess the plugin needs a starting directory to download packages into.

**Comment by roman-kuleshov** [comment]
now have error http://joxi.ru/ZIsyVP3JTJAZXYIXLEA

**Comment by roman-kuleshov** [comment]
after select package to install

**Comment by aaronmschmidt** [comment]
I had the same error. Typing out the complete name of the package in Package Control and hitting return fixed it.

**Comment by wiltherr** [comment]
@nwa-app-01 solution worked for me:
Create a Project (Project/Save Project As)
Restart Sublime
Close the Project (Project/Close Project)
Open the Project
And Bower works

**Comment by afider** [comment]
@nwa-app-01 solution worked for me too

**Comment by ghost** [comment]
@nwa-app-01 solution fixed the problem

**Comment by pinturic** [comment]
I had the same problem in MacOs and for me the solution was 

1) creating a folder in the project
2) add a .bowerrc file to keep the bower configuration

**Comment by benschwarz** [comment]
Ok, so I'd guess that it is failing trying to find a path, and a 'project' changes that. As I said, not a windows user and I don't use this editor any longer. Anyone able to look into it? Happy to talk you through the code…

**Comment by pinturic** [comment]
I use a mac but it was showing the same problem. Moreover after passing to sublime 3 the problem went away

**Comment by wackyjoker** [comment]
@nwa-app-01 Solution Works ! Thank you mate!
