### ISSUE TITLE
bower install not working on ubuntu/linux

### ISSUE THREAD

**Issue by ducin** [benschwarz/sublime-bower#43]
Hi,

I've just installed sublime bower plugin. I've got bower installed properly (and I've been using it for a long time). I've installed the plugin through `browse packages`. Most sublime:bower command work (`discover packages`, `configure project`), but the main one fails - `install`. Following error is thrown: https://github.com/benschwarz/sublime-bower/blob/master/bower/utils/api.py#L30 with this message displayed in sublime:

```
Unable to connect to https://bower.herokuapp.com/packages. Check your internet connection.
```

This seems strange, since my internet connection works perfectly, bower works perfectly from console and I can view the json output of https://bower.herokuapp.com/packages from the browser.

**Comment by lgt** [comment]
I have the same issue

**Comment by bromzh** [comment]
Same trouble. If you try to print exception message, you can see <urlopen error unknown url type: https>
It means that Sublime's python was built without SSL support.
UPD This is old open issue https://github.com/SublimeText/Issues/issues/177

**Comment by octoquad** [comment]
Possibly due to:

``` python
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 526, in run_
    return self.run()
  File "bower.commands.install in /home/bruce/.config/sublime-text-3/Installed Packages/Bower.sublime-package", line 22, in run
  File "bower.commands.install in /home/bruce/.config/sublime-text-3/Installed Packages/Bower.sublime-package", line 27, in list_packages
  File "bower.utils.api in /home/bruce/.config/sublime-text-3/Installed Packages/Bower.sublime-package", line 32, in get
UnboundLocalError: local variable 'response' referenced before assignment
```

**Comment by bromzh** [comment]
@octoquad No, this isn't a reason. This error appears due wrong exception handling: https://github.com/benschwarz/sublime-bower/blob/master/bower/utils/api.py#L28 . The `response` variable which created in `try` block will not be available if error occurs.

**Comment by RyanGannon** [comment]
Is there a workaround for this?
