### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by DougBeney** [benschwarz/sublime-bower#47]
This awesome plugin used to work perfectly. All of the sudden, installing bower components isn't working. 

Here is my error that I ran into in the console:

```
Exception in thread Thread-53:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "bower.utils.download in /Users/dougbeney/Library/Application Support/Sublime Text 3/Installed Packages/Bower.sublime-package", line 22, in run
  File "bower.utils.download in /Users/dougbeney/Library/Application Support/Sublime Text 3/Installed Packages/Bower.sublime-package", line 26, in install_package
  File "bower.utils.cli in /Users/dougbeney/Library/Application Support/Sublime Text 3/Installed Packages/Bower.sublime-package", line 46, in execute
Bower.bower.exceptions.non_clean_exit_error.NonCleanExitError: 1
```

Any ideas?

**Comment by DougBeney** [comment]
I am running macOS Sierra with Sublime build 3126.

I should also mention that 'bower install' works flawlessly in the terminal.

**Comment by Kristinita** [comment]
Bug is reproduced for me in Sublime Text without other plugins and user settings. And I also can successfully install my Bower packages in terminal. @benschwarz?

### Environment

**Operating system and version:**
Windows 32-bit 10.0.14393
**Sublime Text:**
Build 3126


Thanks.
