### ISSUE TITLE
Not working in ST3

### ISSUE THREAD

**Issue by kmmathis** [benschwarz/sublime-bower#7]
I have Bower installed globally, and installed the plugin through the package manager. The Bower command is not showing up for me on Sublime Text 3 on OSX. I get this error in the console on ST3 startup:

`reloading plugin Bower.Bower
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 72, in reload_plugin
    m = importlib.import_module(modulename)
  File "X/importlib/__init__.py", line 88, in import_module
  File "<frozen importlib._bootstrap>", line 1577, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1558, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1525, in _find_and_load_unlocked
  File "/Users/korymathis/Library/Application Support/Sublime Text 3/Installed Packages/Bower.sublime-package/Bower.py", line 8, in <module>
ImportError: No module named 'urllib2'`

I can verify that urllib2 is installed on my computer. It works just fine through the python shell in terminal.

**Comment by benschwarz** [comment]
Thanks for the bug report—I'll look into it.

**Comment by benschwarz** [comment]
At this point, I still have no idea.

@eonlepapillon has opened a pull request to work on the beginnings of getting this to work in ST3, so I'll close this issue and track along on #8.
